### ISSUE TITLE
安装后启用扩展提示报错

### ISSUE THREAD

**Issue by gyp719** [celaraze/dcat-extension-plus#9]
<img width="1424" alt="image" src="https://github.com/celaraze/dcat-extension-plus/assets/30563368/ad2c34bd-3319-4992-9918-449a264591bf">

`[previous exception] [object] (TypeError(code: 0): array_merge(): Argument #1 must be of type array, string given at /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Admin.php:545)
[stacktrace]
#0 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Admin.php(545): array_merge()
#1 /home/vagrant/Code/Tools/storage/framework/views/4782bd99adc991a455d7531b99a0110b.php(7): Dcat\\Admin\\Admin::jsVariables()
#2 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): require('...')
#3 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(125): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#4 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#5 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#6 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()
#7 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#8 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#9 /home/vagrant/Code/Tools/storage/framework/views/0172ce6e4898b11f320709591f185f27.php(33): Illuminate\\View\\View->render()
#10 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): require('...')
#11 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(125): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#12 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#13 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#14 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()
#15 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#16 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#17 /home/vagrant/Code/Tools/storage/framework/views/df21965ae854e9a9e6b433e97f670ec8.php(53): Illuminate\\View\\View->render()
#18 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): require('...')
#19 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(125): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#20 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#21 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#22 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()
#23 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#24 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#25 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Layout/Content.php(524): Illuminate\\View\\View->render()
#26 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Dcat\\Admin\\Layout\\Content->render()
#27 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#28 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(911): Illuminate\\Http\\Response->__construct()
#29 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(878): Illuminate\\Routing\\Router::toResponse()
#30 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Router->prepareResponse()
#31 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#32 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/WebUploader.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\WebUploader->handle()
#34 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/Session.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\Session->handle()
#36 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/Permission.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\Permission->handle()
#38 /home/vagrant/Code/Tools/dcat-admin-extensions/dcat-admin/operation-log/src/Http/Middleware/LogOperation.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\OperationLog\\Http\\Middleware\\LogOperation->handle()
#40 /home/vagrant/Code/Tools/vendor/celaraze/dcat-extension-plus/src/Http/Middleware/MiddleInjectDcatPlus.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Celaraze\\DcatPlus\\Http\\Middleware\\MiddleInjectDcatPlus->handle()
#42 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/Bootstrap.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\Bootstrap->handle()
#44 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/Pjax.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\Pjax->handle()
#46 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/Authenticate.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\Authenticate->handle()
#48 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#50 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#52 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#54 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#56 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#57 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#59 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#61 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/Application.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\Application->handle()
#63 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(800): Illuminate\\Pipeline\\Pipeline->then()
#65 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#66 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#67 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#68 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#69 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#70 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#72 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#73 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#75 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#76 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#78 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#80 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#81 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#82 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#84 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#85 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#86 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#87 /home/vagrant/Code/Tools/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#88 {main}
"} 
`

**Comment by celaraze** [comment]
已经很久没维护了，有空看看。

**Comment by gyp719** [comment]
> 已经很久没维护了，有空看看。

有时间发布一个新版呗

**Comment by celaraze** [comment]
> > 已经很久没维护了，有空看看。
> 
> 有时间发布一个新版呗

好的，这周末我升级下。

**Comment by gyp719** [comment]
> > > 已经很久没维护了，有空看看。
> > 
> > 
> > 有时间发布一个新版呗
> 
> 好的，这周末我升级下。

大佬， 有升级不？

**Comment by gyp719** [comment]
> > > 已经很久没维护了，有空看看。
> > 
> > 
> > 有时间发布一个新版呗
> 
> 好的，这周末我升级下。

大佬， 有空升级下吗
